### ISSUE TITLE
offline plugin not caching all the assets 

### ISSUE THREAD

**Issue by nawrasbaghdadi** [kentcdodds/es6-todomvc#21] opened 2016-09-14 15:23 UTC
Hi , I followed your frontend master course and I tried to implement webpack with offline plufing service worker to a gulp project , so but it is not working fine I posted the question on stackoverflow no answers , can I get any advice 
http://stackoverflow.com/questions/39368597/webpack-offline-plugin-how-to-add-assets-to-sw-js

**Comment by kentcdodds** [comment] 2016-09-14 15:34
I'm not sure, but maybe @NekR will know! :)

**Comment by NekR** [comment] 2016-09-14 16:20
@kentcdodds thanks for pinging me :-)

Hi @nawrasbaghdadi, it's a bit hard to understand what is going on from the code posted on SO. It looks to me like `offline-plugin` by some reasons completely ignores your config, which was never happening before. With you config it should ignore any generated files and cache only your specified files, maybe that is the issue. I'll check that config now, but in a meantime, can you describe what exactly `gulp serve` does?

Better of course would be to get access to your project (or even better to reduced copy which demonstrates the problem), but if that isn't possible I'll try to figure that out as it's now.

**Comment by NekR** [comment] 2016-09-14 16:55
Okay, I just tested and cannot reproduce the issue. I also noticed that `offline-plugin` generates wrong path the generated `bunde.js`, probably something related to the context. Would be really good if I could run it locally and test.

**Comment by nawrasbaghdadi** [comment] 2016-09-15 12:54
@NekR  , please check  this repository https://github.com/nawrasbaghdadi/webpack/tree/master/app
so in the `app` directory is the website I'm testing on you can see also the `node_modules` 
i run `node_modules/.bin/webpack` for generating a webpack and sw.js
and `node_modules/.bin/http-server` to run http server
this repo has all the generated files and folders after adding offline-plugin

**Comment by NekR** [comment] 2016-09-16 22:31
@nawrasbaghdadi  Okay, I just checked your repo and it works for me as expected. But I had some confusion at first. When I was building it, nothing were changing in `dist/` and then I understood that it outputs files into the same folder because you commented this line `path: resolve('dist')`. So maybe you also were looking into wrong folder?

**Comment by nawrasbaghdadi** [comment] 2016-09-18 13:52
@NekR I changed that and pushed it to the same repo , also deploy it to `surge` , you can check it here `https://aback-pear.surge.sh/` , but when you turn off the internet connection, it won't work offline and it is only serving the `bundle.js` file from the service worker , so what am i missing ? it is not coaching all the assets and not working offline

**Comment by kentcdodds** [comment] 2016-09-19 15:29
I'm going to go ahead and close this and unsubscribe. You two feel free to keep things going though if you like :)

**Closed as completed by kentcdodds** 2016-09-19 15:29 UTC

**Comment by NekR** [comment] 2016-09-19 20:09
@nawrasbaghdadi well, SW generated on your website indeed caches only bundle.js. I'll make a fork of your repo and show you how to make it compile correctly. I think you are just missing some bits.

**Comment by nawrasbaghdadi** [comment] 2016-09-22 11:03
@NekR , seems good , thanks
